# Creating node image
FROM node:20-alpine

# Setting the working directory : /app standard convention
WORKDIR /app

# Copy everything from the working directory to the docker container
COPY . .

# Commange to run the application
CMD node hello.js